# Generated by Django 4.0.1 on 2022-02-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
